apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: hackthecrous-front
spec:
  selector:
    app: hackthecrous-front
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP